type: Pefthuggingface_clip_vision
models:
  - name: _pretrained_
    path: openai/clip-vit-base-patch16
    merge_and_unload: false
  - name: sun397
    path: tanganke/clip-vit-base-patch16_sun397_lora-16
  - name: stanford_cars
    path: tanganke/clip-vit-base-patch16_stanford-cars_lora-16
  - name: resisc45
    path: tanganke/clip-vit-base-patch16_resisc45_lora-16
  - name: eurosat
    path: tanganke/clip-vit-base-patch16_eurosat_lora-16
  - name: svhn
    path: tanganke/clip-vit-base-patch16_svhn_lora-16
  - name: gtsrb
    path: tanganke/clip-vit-base-patch16_gtsrb_lora-16
  - name: mnist
    path: tanganke/clip-vit-base-patch16_mnist_lora-16
  - name: dtd
    path: tanganke/clip-vit-base-patch16_dtd_lora-16


# The following datasets are used for test-time adaptation
dataset_type: huggingface_image_classification
tta_datasets:
  - name: sun397
    dataset:
      name: tanganke/sun397
      split: test
  - name: stanford_cars
    dataset:
      name: tanganke/stanford_cars
      split: test
  - name: resisc45
    dataset:
      name: tanganke/resisc45
      split: test
  - name: eurosat
    dataset:
      name: tanganke/eurosat
      split: test
  - name: svhn
    dataset:
      type: instantiate
      name: svhn
      object: 
        _target_: datasets.load_dataset
        _args_:
          - svhn
          - cropped_digits
        split: test
  - name: gtsrb
    dataset:
      name: tanganke/gtsrb
      split: test
  - name: mnist
    dataset:
      name: mnist
      split: test
  - name: dtd
    dataset:
      name: tanganke/dtd
      split: test

train_datasets:
  - name: sun397
    dataset:
      name: tanganke/sun397
      split: train
  - name: stanford_cars
    dataset:
      name: tanganke/stanford_cars
      split: train
  - name: resisc45
    dataset:
      name: tanganke/resisc45
      split: train
  - name: eurosat
    dataset:
      name: tanganke/eurosat
      split: train
  - name: svhn
    dataset:
      type: instantiate
      name: svhn
      object:
        _target_: datasets.load_dataset
        _args_:
          - svhn
          - cropped_digits
        split: train
  - name: gtsrb
    dataset:
      name: tanganke/gtsrb
      split: train
  - name: mnist
    dataset:
      name: mnist
      split: train
  - name: dtd
    dataset:
      name: tanganke/dtd
      split: train
