type: PeftModelForSeq2SeqLMPool
models:
  - name: _pretrained_
    path: google/flan-t5-base
  - name: cola
    path: tanganke/flan-t5-base_glue-cola_lora-16
#    merge_and_unload: false
  - name: mnli
    path: tanganke/flan-t5-base_glue-mnli_lora-16
#    merge_and_unload: false
  - name: mrpc
    path: tanganke/flan-t5-base_glue-mrpc_lora-16
#    merge_and_unload: false
  - name: qnli
    path: tanganke/flan-t5-base_glue-qnli_lora-16
#    merge_and_unload: false
  - name: qqp
    path: tanganke/flan-t5-base_glue-qqp_lora-16
#    merge_and_unload: false
  - name: rte
    path: tanganke/flan-t5-base_glue-rte_lora-16
#    merge_and_unload: false
  - name: sst2
    path: tanganke/flan-t5-base_glue-sst2_lora-16
#    merge_and_unload: false
  - name: stsb
    path: tanganke/flan-t5-base_glue-stsb_lora-16
#    merge_and_unload: false
