type: clip_vit_classification
name: clip-vit-classification_sun397_car

dataset_type: huggingface_image_classification
tasks:
  - name: sun397
    dataset:
      name: tanganke/sun397
      split: test
  - name: stanford_cars
    dataset:
      name: tanganke/stanford_cars
      split: test

clip_model: openai/clip-vit-base-patch32
batch_size: 128
num_workers: 16
fast_dev_run: ${fast_dev_run}
